spring.application.name=SecondDay

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Compay
spring.datasource.username=postgres 
spring.datasource.password=Mayuri123
spring.jpa.hibernate.ddl-auto=update